# ============================================
# TECHIZAT OS - LİGHTDM ANA AYARLAR
# ============================================

[LightDM]
logind-check-graphical=true
user-authority-in-system-dir=false

[Seat:*]
# Greeter
greeter-session=lightdm-gtk-greeter
greeter-hide-users=false
greeter-allow-guest=false

# Varsayılan oturum
user-session=xfce

# Otomatik giriş (kapalı)
autologin-user=
autologin-user-timeout=0

# Ekran ayarları
display-setup-script=
xserver-command=X -dpi 96

[XDMCPServer]
enabled=false

[VNCServer]
enabled=false