#!/bin/sh
set -e

echo "[*] Kali-rolling icin config olusturuluyor..."

lb config noauto \
	--iso-volume "TechizatOS" \
	--distribution "kali-rolling" \
	--parent-distribution "kali-rolling" \
	--archive-areas "main contrib non-free non-free-firmware" \
	--parent-archive-areas "main contrib non-free non-free-firmware" \
	--mirror-bootstrap "https://kali.download/kali" \
	--parent-mirror-bootstrap "https://kali.download/kali" \
	--mirror-binary "https://kali.download/kali" \
	--mirror-chroot "https://kali.download/kali" \
	--mirror-chroot-security "https://kali.download/kali" \
	--mirror-binary-security "https://kali.download/kali" \
	--architectures amd64 \
	--binary-images iso-hybrid \
	--bootloaders "grub-pc grub-efi" \
	--debian-installer none \
	--linux-packages "linux-image" \
	--updates false \
	--security false \
	"${@}"
